name: ci
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'composer.lock'
    branches:
      - '*'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 30
          persist-credentials: false

      - uses: ruby/setup-ruby@180e1d1f1c5eadbfbab3dab6fb79ab0c07e3cecc
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
      - run: bundle install
      - run: bundle exec rake
