name: ci
on:
  push:
    paths:
      - 'lib/**'
      - 'spec/**'
      - 'Gemfile.lock'
      - 'Gemfile'
    branches:
      - '*'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
      - uses: styfle/cancel-workflow-action@0.10.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30
          persist-credentials: false

      - uses: ruby/setup-ruby@v1
      - run: bundle install
      - run: bundle exec rake
